#!/usr/bin/env sh
# 把 community/lists/whitelist.yaml（GitHub 公开维护的白名单源文件）发布到线上 D1。
#
# 这是「PR 提交 → 维护者审核合并 → 生效」链路里唯一需要运营亲手执行的一步：
# 合并 whitelist.yaml 的 PR 后运行本脚本，内容以「文件为唯一事实」整体同步
# （文件里删除的账号会被撤销，不再进快照 whitelist 段）。
#
# 用法:
#   scripts/publish-community-whitelist.sh            # 校验并发布
#   scripts/publish-community-whitelist.sh --check    # 只校验+预览，不写库
#
# 前置:
#   - 已在 apps/community-api/wrangler.local.jsonc 配置好真实的 D1 database_id
#     （该文件已被 gitignore，不入库；与部署共用同一份配置）
#   - 本机 wrangler 已登录（与部署同账号）
set -eu
cd "$(dirname "$0")/.."

source_file="community/lists/whitelist.yaml"
config_dir="apps/community-api"
config="wrangler.local.jsonc"
database="feedsieve-community"

mode="${1:-}"
if [ "$mode" != "" ] && [ "$mode" != "--check" ]; then
  echo "usage: $0 [--check]" >&2
  exit 1
fi

sql_file="$(mktemp "${TMPDIR:-/tmp}/feedsieve-whitelist.XXXXXX.sql")"
trap 'rm -f "$sql_file"' EXIT

python3 - "$source_file" "$mode" "$sql_file" <<'PY'
import re
import sys
import datetime

source_file, mode, sql_file = sys.argv[1], sys.argv[2], sys.argv[3]

HANDLE_RE = re.compile(r'^[A-Za-z0-9_]{1,15}$')
USER_ID_RE = re.compile(r'^\d{1,20}$')

lines = open(source_file, encoding='utf-8').read().splitlines()
entries = []            # 解析出的条目 [{handle, note, name, avatar_url, x_user_id, line}]
cur = None              # 正在构建的条目
expect = None           # 当前条目下一个待吸收字段：'note' -> 'name' -> 'avatar_url' -> 'x_user_id' -> None
in_entries = False
errors = []

def fail(lineno: int, message: str) -> None:
    errors.append(f'{lineno}: {message}')

for lineno, raw in enumerate(lines, start=1):
    stripped = raw.strip()
    if not stripped or stripped.startswith('#'):
        continue
    if stripped == 'entries:' or stripped == 'entries: []':
        in_entries = True
        continue
    if not in_entries:
        if stripped.startswith('schema_version:') or stripped.startswith('updated_at:'):
            continue
        fail(lineno, f'未知顶层字段 {stripped!r}')
        continue
    if stripped.startswith('- handle:'):
        if cur is not None and not cur['note']:
            fail(cur['line'], '条目缺少 note')
        cur = {
            'handle': stripped[len('- handle:'):].strip().strip('"\'').lstrip('@'),
            'note': '',
            'name': None,
            'avatar_url': None,
            'x_user_id': None,
            'line': lineno,
        }
        entries.append(cur)
        expect = 'name'
        continue
    if cur is not None and expect and stripped.startswith(f'{expect}:'):
        value = stripped[len(f'{expect}:'):].strip().strip('"\'')
        if expect == 'note':
            cur['note'] = value
        elif value:
            cur[expect] = value
        # 字段顺序固定 handle -> name -> avatar_url -> note -> x_user_id；吸收完后不再接收条目内字段
        order = ['name', 'avatar_url', 'note', 'x_user_id']
        idx = order.index(expect)
        expect = order[idx + 1] if idx + 1 < len(order) else None
        continue
    if cur is not None and not cur['note']:
        fail(cur['line'], f'条目 {cur["handle"]!r} 缺少 note（字段顺序: - handle: / name: / avatar_url: / note: / x_user_id:）')
        cur = None
        expect = None
    fail(lineno, f'期望新的 "- handle:" 条目，实际 {stripped!r}')
if cur is not None and not cur['note']:
    fail(cur['line'], '条目缺少 note')

seen = set()
for entry in entries:
    handle = entry['handle'].lower()
    if not HANDLE_RE.match(handle):
        fail(entry['line'], f'handle 非法: {entry["handle"]!r}')
    if handle in seen:
        fail(entry['line'], f'handle 重复: @{handle}')
    seen.add(handle)
    if not 4 <= len(entry['note']) <= 240:
        fail(entry['line'], f'note 需 4-240 字（当前 {len(entry["note"])}）')
    if entry['x_user_id'] is not None and not USER_ID_RE.match(entry['x_user_id']):
        fail(entry['line'], f'x_user_id 非法: {entry["x_user_id"]!r}')
    if entry['name'] is not None and not 1 <= len(entry['name']) <= 40:
        fail(entry['line'], f'name 需 1-40 字: {entry["name"]!r}')
    if entry['avatar_url'] is not None and not entry['avatar_url'].startswith('https://pbs.twimg.com/profile_images/'):
        fail(entry['line'], f'avatar_url 必须是 pbs.twimg.com 公开头像: {entry["avatar_url"]!r}')

if errors:
    for error in errors:
        print(f'error: {source_file}:{error}')
    sys.exit(1)

print(f'whitelist.yaml ok: {len(entries)} 条待发布')
for entry in entries:
    x_user_id = f' ({entry["x_user_id"]})' if entry['x_user_id'] else ''
    print(f'  + @{entry["handle"].lower()}{x_user_id}  {entry["note"]}')

if mode == '--check':
    sys.exit(0)

now = int(datetime.datetime.now(datetime.timezone.utc).timestamp())
stamp = datetime.datetime.now(datetime.timezone.utc).isoformat()

out = [
    f'-- generated by publish-community-whitelist.sh from {source_file}',
    f'-- {len(entries)} entries · {stamp} · 文件为唯一事实，先全量撤销再 upsert',
    # 先撤销：文件中已删除的账号从白名单移除（并记审计）
    f'UPDATE maintainer_whitelist SET active = 0, updated_at = {now} WHERE active = 1;',
    f"INSERT INTO maintainer_whitelist_audit (action, handle, note, created_at) "
    f"SELECT 'remove', handle, note, {now} FROM maintainer_whitelist WHERE active = 0 AND updated_at = {now};",
]
for entry in entries:
    handle = entry['handle'].lower()
    note = entry['note'].replace("'", "''")
    name = (entry['name'] or '').replace("'", "''")
    avatar_url = (entry['avatar_url'] or '').replace("'", "''")
    x_user_id = entry['x_user_id'] or ''
    name_sql = 'NULL' if not name else "'" + name + "'"
    avatar_sql = 'NULL' if not avatar_url else "'" + avatar_url + "'"
    out.append(
        f"INSERT INTO maintainer_whitelist (handle, x_user_id, name, avatar_url, note, active, created_at, updated_at) "
        f"VALUES ('{handle}', {'NULL' if not x_user_id else f"'{x_user_id}'"}, "
        f"{name_sql}, {avatar_sql}, '{note}', 1, {now}, {now}) "
        f"ON CONFLICT(handle) DO UPDATE SET "
        f"x_user_id = COALESCE(excluded.x_user_id, maintainer_whitelist.x_user_id), "
        f"name = COALESCE(excluded.name, maintainer_whitelist.name), "
        f"avatar_url = COALESCE(excluded.avatar_url, maintainer_whitelist.avatar_url), "
        f"note = excluded.note, active = 1, updated_at = excluded.updated_at;",
    )
    out.append(
        f"INSERT INTO maintainer_whitelist_audit (action, handle, note, created_at) "
        f"VALUES ('update', '{handle}', '{note}', {now});",
    )
with open(sql_file, 'w', encoding='utf-8') as f:
    f.write('\n'.join(out) + '\n')
PY

if [ -z "$mode" ]; then
  echo "publishing to D1 ($database)…"
  (cd "$config_dir" && pnpm exec wrangler d1 execute "$database" --remote --config "$config" --file "$sql_file")

  # D1 同步完成后立即触发快照发布（人工发布通道，绕开当日一版节流）。
  # 这是唯一的生效入口：脚本直写 D1 不会置快照脏标记，cron 不感知，必须在这里显式收尾。
  base="${FEEDSIEVE_API:-$(cat "$HOME/.config/feedsieve/api-base" 2>/dev/null || true)}"
  key="${FEEDSIEVE_AGENT_KEY:-$(cat "${FEEDSIEVE_AGENT_KEY_FILE:-$HOME/.config/feedsieve/agent.key}" 2>/dev/null || true)}"
  if [ -z "$base" ] || [ -z "$key" ]; then
    echo "warning: 缺少 agent API 配置，快照未发布——白名单要等下一次 cron 版本号滚动才可见" >&2
    exit 0
  fi
  echo "publishing snapshot…"
  if ! curl -fsSL -X POST -H "x-agent-key: $key" -H 'content-type: application/json' "$base/api/agent/accounts/publish"; then
    echo "error: 快照发布失败，白名单已入库但没有随快照可见（重跑本脚本或调用 /api/agent/accounts/publish）" >&2
    exit 1
  fi
  echo "published. 快照与白名单均已生效。"
fi