#!/usr/bin/env sh
# 把 community/lists/whitelist.yaml（GitHub 公开维护的白名单源文件）发布到线上 D1。
#
# 这是「PR 提交 → 维护者审核合并 → 生效」链路里唯一需要运营亲手执行的一步：
# 合并 whitelist.yaml 的 PR 后运行本脚本，内容以「文件为唯一事实」整体同步
# （文件里删除的账号会被撤销，不再进快照 whitelist 段）。
#
# 用法:
#   scripts/publish-community-whitelist.sh            # 校验并发布
#   scripts/publish-community-whitelist.sh --check    # 只校验+预览，不写库
#
# 前置:
#   - 已在 apps/community-api/wrangler.local.jsonc 配置好真实的 D1 database_id
#     （该文件已被 gitignore，不入库；与部署共用同一份配置）
#   - 本机 wrangler 已登录（与部署同账号）
set -eu
cd "$(dirname "$0")/.."

source_file="community/lists/whitelist.yaml"
config_dir="apps/community-api"
config="wrangler.local.jsonc"
database="feedsieve-community"

mode="${1:-}"
if [ "$mode" != "" ] && [ "$mode" != "--check" ]; then
  echo "usage: $0 [--check]" >&2
  exit 1
fi

sql_file="$(mktemp "${TMPDIR:-/tmp}/feedsieve-whitelist.XXXXXX.sql")"
trap 'rm -f "$sql_file"' EXIT

python3 - "$source_file" "$mode" "$sql_file" <<'PY'
import re
import sys
import datetime

source_file, mode, sql_file = sys.argv[1], sys.argv[2], sys.argv[3]

HANDLE_RE = re.compile(r'^[A-Za-z0-9_]{1,15}$')
USER_ID_RE = re.compile(r'^\d{1,20}$')

lines = open(source_file, encoding='utf-8').read().splitlines()
entries = []            # 解析出的条目 [{handle, note, x_user_id, line}]
cur = None              # 正在构建的条目
expect = None           # 当前条目下一个待吸收字段：'note' -> 'x_user_id' -> None
in_entries = False
errors = []

def fail(lineno: int, message: str) -> None:
    errors.append(f'{lineno}: {message}')

for lineno, raw in enumerate(lines, start=1):
    stripped = raw.strip()
    if not stripped or stripped.startswith('#'):
        continue
    if stripped == 'entries:' or stripped == 'entries: []':
        in_entries = True
        continue
    if not in_entries:
        if stripped.startswith('schema_version:') or stripped.startswith('updated_at:'):
            continue
        fail(lineno, f'未知顶层字段 {stripped!r}')
        continue
    if stripped.startswith('- handle:'):
        if cur is not None and not cur['note']:
            fail(cur['line'], '条目缺少 note')
        cur = {
            'handle': stripped[len('- handle:'):].strip().strip('"\'').lstrip('@'),
            'note': '',
            'x_user_id': None,
            'line': lineno,
        }
        entries.append(cur)
        expect = 'note'
        continue
    if cur is not None and expect and stripped.startswith(f'{expect}:'):
        value = stripped[len(f'{expect}:'):].strip().strip('"\'')
        if expect == 'note':
            cur['note'] = value
        elif value:
            cur['x_user_id'] = value
        # 字段顺序固定 note -> x_user_id；x_user_id 吸收完后不再接收条目内字段
        expect = None if expect == 'x_user_id' else 'x_user_id'
        continue
    if cur is not None and not cur['note']:
        fail(cur['line'], f'条目 {cur["handle"]!r} 缺少 note（字段顺序: - handle: / note: / x_user_id:）')
        cur = None
        expect = None
    fail(lineno, f'期望新的 "- handle:" 条目，实际 {stripped!r}')
if cur is not None and not cur['note']:
    fail(cur['line'], '条目缺少 note')

seen = set()
for entry in entries:
    handle = entry['handle'].lower()
    if not HANDLE_RE.match(handle):
        fail(entry['line'], f'handle 非法: {entry["handle"]!r}')
    if handle in seen:
        fail(entry['line'], f'handle 重复: @{handle}')
    seen.add(handle)
    if not 4 <= len(entry['note']) <= 240:
        fail(entry['line'], f'note 需 4-240 字（当前 {len(entry["note"])}）')
    if entry['x_user_id'] is not None and not USER_ID_RE.match(entry['x_user_id']):
        fail(entry['line'], f'x_user_id 非法: {entry["x_user_id"]!r}')

if errors:
    for error in errors:
        print(f'error: {source_file}:{error}')
    sys.exit(1)

print(f'whitelist.yaml ok: {len(entries)} 条待发布')
for entry in entries:
    x_user_id = f' ({entry["x_user_id"]})' if entry['x_user_id'] else ''
    print(f'  + @{entry["handle"].lower()}{x_user_id}  {entry["note"]}')

if mode == '--check':
    sys.exit(0)

now = int(datetime.datetime.now(datetime.timezone.utc).timestamp())
stamp = datetime.datetime.now(datetime.timezone.utc).isoformat()

out = [
    f'-- generated by publish-community-whitelist.sh from {source_file}',
    f'-- {len(entries)} entries · {stamp} · 文件为唯一事实，先全量撤销再 upsert',
    # 先撤销：文件中已删除的账号从白名单移除（并记审计）
    f'UPDATE maintainer_whitelist SET active = 0, updated_at = {now} WHERE active = 1;',
    f"INSERT INTO maintainer_whitelist_audit (action, handle, note, created_at) "
    f"SELECT 'remove', handle, note, {now} FROM maintainer_whitelist WHERE active = 0 AND updated_at = {now};",
]
for entry in entries:
    handle = entry['handle'].lower()
    note = entry['note'].replace("'", "''")
    x_user_id = entry['x_user_id'] or ''
    out.append(
        f"INSERT INTO maintainer_whitelist (handle, x_user_id, note, active, created_at, updated_at) "
        f"VALUES ('{handle}', {'NULL' if not x_user_id else f"'{x_user_id}'"}, '{note}', 1, {now}, {now}) "
        f"ON CONFLICT(handle) DO UPDATE SET "
        f"x_user_id = COALESCE(excluded.x_user_id, maintainer_whitelist.x_user_id), "
        f"note = excluded.note, active = 1, updated_at = excluded.updated_at;",
    )
    out.append(
        f"INSERT INTO maintainer_whitelist_audit (action, handle, note, created_at) "
        f"VALUES ('update', '{handle}', '{note}', {now});",
    )
with open(sql_file, 'w', encoding='utf-8') as f:
    f.write('\n'.join(out) + '\n')
PY

if [ -z "$mode" ]; then
  echo "publishing to D1 ($database)…"
  (cd "$config_dir" && pnpm exec wrangler d1 execute "$database" --remote --config "$config" --file "$sql_file")
  echo "published. 快照由 cron 按「当日一版」节流发布；想立即生效可在社区后台点显式发布。"
fi